
# ============================================================
# Airflow configurations
# ============================================================
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.5.0}
  # build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://db_user:db_password@asb-postgres-db/airflow
    # For backward compatibility, with Airflow <2.3
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://db_user:db_password@asb-postgres-db/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/scripts:/opt/airflow/scripts
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    asb-postgres-db:
      condition: service_healthy

services:
  # ============================================================
  # 1.0 - SeaweedFS for S3-like storage 
  # ============================================================
  asb-seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: asb-seaweedfs
    command: "mini -dir=/data"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      S3_BUCKET: warehouse
    
    # host:container port mapping. Make sure that the host ports 
    # are available and not used in other compose files
    ports:
      - "8333:8333"   # S3 API
      - "9333:9333"   # Master UI
      - "8889:8888"   # Filer UI
    volumes:
      - asb_seaweedfs_data:/data

  # ============================================================
  # 1.1 - SeaweedFS initialization script to create data-lake bucket
  # ============================================================
  asb-seaweedfs-init:
    image: chrislusf/seaweedfs:latest
    container_name: asb-seaweedfs-init

    depends_on:
      - asb-seaweedfs

    entrypoint: /bin/sh
    command:
      - -c
      - |
        sleep 5
        echo "s3.bucket.create -name data-lake" | \
          weed shell \
            -master=asb-seaweedfs:9333 \
            -filer=asb-seaweedfs:8888

  # ============================================================
  # 2.0 - PostgreSQL database for OLTP, OLAP, and metadata databases  
  # ============================================================
  asb-postgres-db:
    image: postgres:16-alpine
    container_name: asb-postgres-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: asb_oltp
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - asb_postgres_data:/var/lib/postgresql/data
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U db_user -d asb_oltp"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # ============================================================
  # 3.0 - Iceberg Open Table format for lakehouses
  # ============================================================
  asb-iceberg-rest:
    image: apache/iceberg-rest-fixture:latest
    container_name: asb-iceberg-rest

    depends_on:
      - asb-seaweedfs

    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1

      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://asb-seaweedfs:8333
      CATALOG_S3_PATH__STYLE__ACCESS: "true"

    ports:
      - "8181:8181"

  # ============================================================
  # 4.0 - Spark for distributed processing
  # ============================================================
  asb-spark-iceberg:
    image: tabulario/spark-iceberg:latest
    container_name: asb-spark-iceberg

    depends_on:
      - asb-iceberg-rest
      - asb-seaweedfs

    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
      PYSPARK_SUBMIT_ARGS: >-
        --packages org.apache.hadoop:hadoop-aws:3.3.4
        --conf spark.jars.ivy=/opt/spark/ivy-cache
        pyspark-shell


    ports:
      - "8888:8888"     # Jupyter UI
      - "8080:8080"     # Spark Master UI
      - "10000:10000"
      - "10001:10001"

    volumes:
      - ./setup/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./airflow/scripts:/opt/spark/scripts:ro
      - asb_spark_ivy_cache:/opt/spark/ivy-cache

  # ============================================================
  # 5.0 - Trino for distributed SQL query engine for big data analytics
  # ============================================================
  asb-trino:
    image: trinodb/trino:latest
    container_name: asb-trino

    depends_on:
      - asb-iceberg-rest
      - asb-seaweedfs

    ports:
      - "8081:8080"

    volumes:
      - ./setup/iceberg.properties:/etc/trino/catalog/iceberg.properties:ro

  # ============================================================
  # 6.0 - Airflow web server UI
  # ============================================================
  asb-airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8082:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      asb-airflow-init:
        condition: service_completed_successfully

  # ============================================================
  # 6.1 - Airflow Scheduler for DAG scheduling
  # ============================================================
  asb-airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      asb-airflow-init:
        condition: service_completed_successfully

  # ============================================================
  # 6.2 - Airflow Triggerer to trigger tasks
  # ============================================================
  asb-airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      asb-airflow-init:
        condition: service_completed_successfully

  # ============================================================
  # 6.3 - Airflow initialization scripts
  # ============================================================
  asb-airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        function ver() {
          printf "%04d%04d%04d%04d" $${1//./ }
        }
        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
        airflow_version_comparable=$$(ver $${airflow_version})
        min_airflow_version=2.2.0
        min_airflow_version_comparable=$$(ver $${min_airflow_version})
        if (( airflow_version_comparable < min_airflow_version_comparable )); then
          echo
          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
          echo
          exit 1
        fi
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/airflow/logs /sources/airflow/dags /sources/airflow/plugins /sources/airflow/scripts
        chown -R "${AIRFLOW_UID}:0" /sources/airflow/{logs,dags,plugins,scripts}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - .:/sources

  # ============================================================
  # 6.4 - Airflow workaround entrypoint issue fix 
  # ============================================================
  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow

  # ============================================================
  # 7.0 - Metabase open source dashboarding platform
  # ============================================================
  asb-metabase:
    image: metabase/metabase:v0.63.17.x
    container_name: asb-metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: db_user
      MB_DB_PASS: db_password
      MB_DB_HOST: asb-postgres-db
    depends_on:
      - asb-postgres-db

  # ============================================================
  # 8.0 - Cloudbeaver / DBeaver web-based database management tool
  # ============================================================
  asb-cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: asb-cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - asb_cloudbeaver_workspace:/opt/cloudbeaver/workspace
      # Mount DuckDB files as read-only
      - ./setup/03_duckdb_databases:/opt/cloudbeaver/duckdb:ro
    restart: unless-stopped
    depends_on:
      asb-setup:
        condition: service_completed_successfully

  # ============================================================
  # 9.0 - Python script to load AdventureWorks data to PostgreSQL and DuckDB
  # ============================================================
  asb-setup:
    image: python:3.11-slim
    container_name: asb-setup
    working_dir: /app

    environment:
      # DuckDB file created inside the mounted project directory
      DUCKDB_OLTP_CONNECTION: /app/setup/03_duckdb_databases/asb_oltp.duckdb
      DUCKDB_OLAP_CONNECTION: /app/setup/03_duckdb_databases/asb_olap.duckdb

      # Use the Compose service name—not localhost
      POSTGRES_HOST: asb-postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB_OLTP: asb_oltp
      POSTGRES_DB_OLAP: asb_olap
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password

    volumes:
      # Requirements.txt file for Python packages 
      - ./requirements.txt:/app/requirements.txt:ro

      # Map setup_db.py and setup folder to the container
      - ./setup_db.py:/app/setup_db.py
      - ./setup/01_data_files:/app/setup/01_data_files
      - ./setup/02_sql_duckdb:/app/setup/02_sql_duckdb
      - ./setup/03_duckdb_databases:/app/setup/03_duckdb_databases

    command:
      - sh
      - -c
      - |
        pip install -r /app/requirements.txt &&
        python -u setup_db.py

    depends_on:
      asb-postgres-db:
        condition: service_healthy

    restart: "no"

volumes:
  asb_seaweedfs_data:
  asb_postgres_data:
  asb_cloudbeaver_workspace:
  asb_spark_ivy_cache:
